apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/rfielding/mounts/mongo"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gmdata-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/rfielding/mounts/gmd"
