#!/bin/bash

#(
#sudo mkdir ~/mounts
#sudo chmod 777 ~/mounts
#sudo mkdir  ~/mounts/mongo
#sudo chmod 777 ~/mounts/mongo # serve mongo database from here
#sudo mkdir ~/mounts/gmd
#sudo chmod 777 ~/mounts/gmd # serve blobs out of gmdata, when S3 isn't used. requires root :-(
#sudo mkdir ~/mounts/gmdata # ?? is this named after the CLUSTER?
#sudo chmod 777 ~/mounts/gmdata
#)

kubectl create namespace greymatter-gmd
echo ----- PROJECT GITHUB SECRET -----
ssh-keyscan github.com > known_hosts
kubectl create secret generic greymatter-sync-secret \
        --from-file=ssh-private-key=$(echo ~/).ssh/id_rsa \
        --from-file=known_hosts=known_hosts \
        -n greymatter-gmd


kubectl apply -f cfg/pv.yaml
kubectl apply -f cfg/cm.yaml

kubectl apply -f app/zk.yaml           # persistent
kubectl apply -f app/kafkadata.yaml    # persistent
kubectl apply -f app/jwt.yaml
kubectl apply -f app/mongo.yaml        # persistent
kubectl apply -f app/gmdata.yaml       # persistent when not using S3
##kubectl apply -n greymatter-gmd -f app/redis.yaml
kubectl apply -f k8s
